#!/usr/bin/env bash

nix_wrapped_install() {
    pkg=$1
    query_cmd="nix-env -q $pkg"
    install_cmd="nix-env -iA nixpkgs.$pkg"

    if [ -z $1 ];then
        echo "please pass a pkg to install."
        return
    fi

    msg=$($query_cmd)

    if [[ $? == "1" ]];then
        echo $msg
        exit 0
    fi

    if [ ! -z msg ];then
        echo -e "$msg has installed"
        exit 0
    fi

    echo -e "start install $pkg:\n"
    $($install_cmd)
}

nix_wrapped_install $@
