#!/usr/bin/env python3

# vi: ft=python


import subprocess

import click


@click.command()
@click.argument("work_dir", type=click.Path(exists=True), default=".")
@click.option("-f", "--file", type=click.Path(exists=False), help="File to open")
@click.option("-t", "--tmp", is_flag=True, help="Use temporary file")
def cli(work_dir, file, tmp):
    base_cmd = "wezterm cli spawn --new-window " + (
        f"--cwd {work_dir}" if work_dir else ""
    )
    if tmp:
        cmd = f"{base_cmd} -- nvim ~/tmp/tmp_nvim.txt"
    elif file:
        cmd = f"{base_cmd} -- nvim {file}"
    else:
        cmd = f"{base_cmd} -- nvim"

    subprocess.run(cmd, shell=True, check=True)


if __name__ == "__main__":
    cli()
