#!/usr/bin/env python3

# vi: ft=python


import subprocess

import click


@click.command()
@click.argument("work_dir", type=click.Path(exists=True), default=".")
def cli(work_dir):
    cmd = "wezterm cli spawn --new-window " + (f"--cwd {work_dir}" if work_dir else "")
    subprocess.run(cmd, shell=True, check=True)


if __name__ == "__main__":
    cli()
