name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'build')"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v7
        with:
          name: arcueid
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: |
          nix-build nix-extra
          nix-build nix-emacs
          ./bootstrap.sh

  build-macos-latest:
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, 'build')"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v7
        with:
          name: arcueid
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: |
          nix-build nix-extra
          nix-build nix-emacs
          ./bootstrap.sh

  # build-macos-11:
  #   runs-on: macos-11.0
  #   steps:
  #     - uses: actions/checkout@v2.3.4
  #     - uses: cachix/install-nix-action@v12
  #       with:
  #         nix_path: nixpkgs=channel:nixos-unstable
  #     - uses: cachix/cachix-action@v7
  #       with:
  #         name: arcueid
  #         signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
  #     - run: nix-build
