name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'build')"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: arcueid
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: |
          nix-channel --list
          nix-channel --remove nixpkgs
          nix-channel --add https://mirrors.tuna.tsinghua.edu.cn/nix-channels/nixpkgs-unstable nixpkgs
          nix-channel --update
          nix-env -i -f default.nix

  build-macos-latest:
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, 'build')"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: arcueid
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: |
          nix-channel --list
          nix-channel --remove nixpkgs
          nix-channel --add https://mirrors.tuna.tsinghua.edu.cn/nix-channels/nixpkgs-unstable nixpkgs
          nix-channel --update
          nix-env -i -f default.nix
